[[databases]]
name = "Test database 1 - PostgreSQL"
database = "devdb"
type = "postgresql"
username = "devuser"
password = "changeme"
port = 5432
host = "db-postgres"
generated_id = "16678159-ff7e-4c97-8c83-0adeff214689"

[[databases]]
name = "Test database 2 - MariaDB"
database = "mariadb"
type = "mysql"
username = "mariadb"
password = "changeme"
port = 3306
host = "db-mariadb"
generated_id = "16678124-ff7e-4c97-8c83-0adeff214667"

[[databases]]
name = "Test database 3 - MongoDB Auth"
database = "testdbauth"
type = "mongodb"
username = "root"
password = "rootpassword"
port = 27017
host = "db-mongodb-auth"
generated_id = "16678145-ff7e-4c97-8c83-0adeff214681"

[[databases]]
name = "Test database 3 - MongoDB"
database = "testdb"
type = "mongodb"
username = ""
password = ""
port = 27017
host = "db-mongodb"
generated_id = "16678147-ff7e-4c97-8c83-0adeff214681"
